import { communityLessonsTable, db, usersTable, type CommunityExercise, type CommunityWord } from "../../lib/db/src/index.ts";

const COMMUNITY_AUTHOR_ID = "community-seed-author";
const COMMUNITY_AUTHOR_EMAIL = "community+seed@duotr.local";

type SeedLesson = {
  id: string;
  title: string;
  description: string;
  category: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  sourceLanguage: string;
  targetLanguage: string;
  icon: string;
  tags: string[];
  objectives: string[];
  estimatedMinutes: number;
  words: CommunityWord[];
  exercises: CommunityExercise[];
};

const lessons: SeedLesson[] = [
  {
    id: "community-seed-cafe-ordering",
    title: "Kafede Siparis Verme",
    description: "Bir kafede siparis verirken kullanilan temel kaliplari pratik et.",
    category: "Gunluk Hayat",
    difficulty: "beginner",
    sourceLanguage: "Turkish",
    targetLanguage: "English",
    icon: "☕",
    tags: ["kafe", "siparis", "konusma", "baslangic"],
    objectives: [
      "Icecek siparisi verebilmek",
      "Miktar ve boy secenegi ifade etmek",
      "Kasada kisa cevaplar kurabilmek",
    ],
    estimatedMinutes: 6,
    words: [
      { id: "cafe-word-1", term: "filtre kahve", translation: "filter coffee", example: "Bir filtre kahve alabilir miyim?", note: "Siparis kalibi icin kullan." },
      { id: "cafe-word-2", term: "orta boy", translation: "medium size", example: "Orta boy olsun.", note: "Boy belirtirken." },
      { id: "cafe-word-3", term: "paket olsun", translation: "to go", example: "Paket olsun, lutfen.", note: "Amerikan Ingilizcesi." },
      { id: "cafe-word-4", term: "hesap", translation: "bill", example: "Hesabi alabilir miyim?", note: "Cafe cikisinda." },
    ],
    exercises: [
      {
        id: "cafe-ex-1",
        type: "multiple-choice",
        prompt: "\"Bir latte alabilir miyim?\" cumlesinin en dogru Ingilizcesi hangisi?",
        instructions: "En dogal siparis kalibini sec.",
        options: ["Can I get a latte?", "I am latte.", "Give me coffee now.", "Latte where?"],
        correctAnswers: ["Can I get a latte?"],
        hint: "Nazik siparis sorusu.",
        explanation: "\"Can I get...?\" gunluk sipariste cok kullanilir.",
      },
      {
        id: "cafe-ex-2",
        type: "matching",
        prompt: "Kafe ifadelerini eslestir.",
        instructions: "Sol taraftaki Turkce ifadeyi dogru Ingilizce karsiligiyla birlestir.",
        pairs: [
          { id: "cafe-pair-1", left: "paket olsun", right: "to go" },
          { id: "cafe-pair-2", left: "orta boy", right: "medium size" },
          { id: "cafe-pair-3", left: "hesap", right: "bill" },
        ],
        hint: "Birisi boy, birisi odeme, birisi paket.",
        explanation: "Kafe dilinde en sik kullanilan mini kaliplar bunlar.",
      },
      {
        id: "cafe-ex-3",
        type: "fill-blank",
        prompt: "\"Can I get a ___ coffee?\"",
        instructions: "Boslugu dogru icecek ifadesiyle doldur.",
        correctAnswers: ["filter", "filter coffee"],
        hint: "Kelime bankasindaki ilk ifade yardimci olacak.",
        explanation: "Filter coffee ifadesi dogrudan icecek adidir.",
      },
      {
        id: "cafe-ex-4",
        type: "speech-to-text",
        prompt: "Dinle ve yaz.",
        instructions: "Okunan cumleyi ayni sekilde yaz.",
        voiceText: "Can I get a medium latte to go?",
        correctAnswers: ["Can I get a medium latte to go?"],
        hint: "Hem boy hem paket bilgisi var.",
        explanation: "Siparis kalibinda urun + boy + to go sirasi kullanildi.",
      },
      {
        id: "cafe-ex-5",
        type: "translate-written",
        prompt: "Cumleyi Ingilizceye cevir.",
        instructions: "Kasada soylenebilecek dogal bir ceviri yaz.",
        sourceText: "Hesabi alabilir miyim?",
        correctAnswers: ["Can I get the bill?", "Could I get the bill?"],
        hint: "Bill kelimesini kullan.",
        explanation: "Bill veya check iki dogru secenektir; burada bill kabul ediliyor.",
      },
    ],
  },
  {
    id: "community-seed-airport-checkin",
    title: "Havaalani Check-in",
    description: "Check-in bankosunda gerekli sorulara cevap verebilmek icin hizli pratik seti.",
    category: "Seyahat",
    difficulty: "intermediate",
    sourceLanguage: "Turkish",
    targetLanguage: "English",
    icon: "✈️",
    tags: ["havaalani", "seyahat", "check-in", "konusma"],
    objectives: [
      "Pasaport ve bagaj sorularini anlayabilmek",
      "Koltuk tercihini ifade edebilmek",
      "Kisa check-in diyaloglari kurabilmek",
    ],
    estimatedMinutes: 7,
    words: [
      { id: "airport-word-1", term: "el bagaji", translation: "carry-on", example: "Sadece el bagajim var.", note: "Kabin bagaji ile ayni anlamda." },
      { id: "airport-word-2", term: "koridor koltugu", translation: "aisle seat", example: "Koridor koltugu tercih ederim.", note: "Window seat ile karsit." },
      { id: "airport-word-3", term: "boarding pass", translation: "boarding pass", example: "Boarding pass burada.", note: "Dogrudan kullanilir." },
      { id: "airport-word-4", term: "bagaj teslim etmek", translation: "check a bag", example: "Bir bagaj teslim etmek istiyorum.", note: "Fiil kalibi." },
    ],
    exercises: [
      {
        id: "airport-ex-1",
        type: "multiple-choice",
        prompt: "\"Koridor koltugu istiyorum\" ifadesine en yakin secenek hangisi?",
        instructions: "Check-in bankosunda soylenebilecek en uygun cevabi sec.",
        options: ["I want an aisle seat.", "I am in the window.", "My bag is seat.", "Seat wants me."],
        correctAnswers: ["I want an aisle seat."],
        hint: "Aisle seat = koridor koltugu.",
        explanation: "Aisle seat en dogrudan ve dogru ifadedir.",
      },
      {
        id: "airport-ex-2",
        type: "matching",
        prompt: "Seyahat terimlerini dogru karsiliklariyla eslestir.",
        instructions: "Her Turkce ifadeyi uygun Ingilizce terime bagla.",
        pairs: [
          { id: "airport-pair-1", left: "el bagaji", right: "carry-on" },
          { id: "airport-pair-2", left: "koridor koltugu", right: "aisle seat" },
          { id: "airport-pair-3", left: "bagaj teslim etmek", right: "check a bag" },
        ],
        hint: "Uc ifade de seyahat baglaminda cok yaygin.",
        explanation: "Check-in diyaloglari bu uc terim etrafinda doner.",
      },
      {
        id: "airport-ex-3",
        type: "fill-blank",
        prompt: "\"I only have a ___.\"",
        instructions: "Boslugu bagaj turuyle doldur.",
        correctAnswers: ["carry-on"],
        hint: "Kabin icine alinan bagaj.",
        explanation: "\"Carry-on\" kabine alinabilen bagaj icin kullanilir.",
      },
      {
        id: "airport-ex-4",
        type: "speech-to-text",
        prompt: "Dinle ve check-in cevabini yaz.",
        instructions: "Okunan cumleyi yaz.",
        voiceText: "I would like an aisle seat, please.",
        correctAnswers: ["I would like an aisle seat, please."],
        hint: "Nazik bir koltuk tercihi cumlesi.",
        explanation: "\"I would like...\" resmi ama yaygin bir kaliptir.",
      },
      {
        id: "airport-ex-5",
        type: "translate-written",
        prompt: "Cumleyi Ingilizceye cevir.",
        instructions: "Check-in gorevlisine soylenebilecek dogal bir cumle kur.",
        sourceText: "Bir bagaj teslim etmek istiyorum.",
        correctAnswers: ["I would like to check a bag.", "I want to check a bag."],
        hint: "check a bag kalibini kullan.",
        explanation: "Check a bag, bagaji teslim etmeyi anlatir.",
      },
    ],
  },
  {
    id: "community-seed-remote-meeting",
    title: "Uzaktan Toplanti Dili",
    description: "Online toplantilarda soz almak, ekran paylasmak ve netlestirme istemek icin pratik seti.",
    category: "Is Ingilizcesi",
    difficulty: "intermediate",
    sourceLanguage: "Turkish",
    targetLanguage: "English",
    icon: "💼",
    tags: ["toplanti", "is", "uzaktan-calisma", "sunum"],
    objectives: [
      "Toplantida soz isteyebilmek",
      "Teknik aksakligi kisa ifade etmek",
      "Netlestirme ve tekrar isteme kaliplari kurabilmek",
    ],
    estimatedMinutes: 8,
    words: [
      { id: "meeting-word-1", term: "ekran paylasmak", translation: "share my screen", example: "Ekranimi paylasayim.", note: "Toplanti girisinde cok kullanilir." },
      { id: "meeting-word-2", term: "bir noktayi netlestirmek", translation: "clarify a point", example: "Bir noktayi netlestirmek istiyorum.", note: "Profesyonel ton." },
      { id: "meeting-word-3", term: "sesim geliyor mu?", translation: "Can you hear me?", example: "Sesim geliyor mu?", note: "Mikrofon kontrolu." },
      { id: "meeting-word-4", term: "soz almak", translation: "jump in", example: "Bir sey eklemek icin girebilir miyim?", note: "Daha dogal toplanti dili." },
    ],
    exercises: [
      {
        id: "meeting-ex-1",
        type: "multiple-choice",
        prompt: "\"Bir noktayi netlestirmek istiyorum\" ifadesine en yakin secenek hangisi?",
        instructions: "Profesyonel toplanti diline uygun cevabi sec.",
        options: ["I would like to clarify a point.", "I am a point.", "Point is me.", "Clarify is gone."],
        correctAnswers: ["I would like to clarify a point."],
        hint: "Clarify a point kalibini hatirla.",
        explanation: "Bu ifade toplantida soz almanin dogal yollarindan biridir.",
      },
      {
        id: "meeting-ex-2",
        type: "matching",
        prompt: "Toplanti kaliplarini eslestir.",
        instructions: "Turkce ve Ingilizce toplanti ifadelerini birlestir.",
        pairs: [
          { id: "meeting-pair-1", left: "ekran paylasmak", right: "share my screen" },
          { id: "meeting-pair-2", left: "sesim geliyor mu?", right: "Can you hear me?" },
          { id: "meeting-pair-3", left: "bir noktayi netlestirmek", right: "clarify a point" },
        ],
        hint: "Teknik ve iletisim kaliplari birlikte.",
        explanation: "Bu uc kalip online toplantilarda en cok kullanilanlardan.",
      },
      {
        id: "meeting-ex-3",
        type: "fill-blank",
        prompt: "\"Can you ___ me?\"",
        instructions: "Mikrofon kontrolu icin eksik kelimeyi yaz.",
        correctAnswers: ["hear"],
        hint: "Ses ile ilgili.",
        explanation: "Can you hear me? online toplantilarin klasik kontrol cumlesidir.",
      },
      {
        id: "meeting-ex-4",
        type: "speech-to-text",
        prompt: "Dinle ve toplanti kalibini yaz.",
        instructions: "Okunan cumleyi ayni sekilde yaz.",
        voiceText: "Let me share my screen.",
        correctAnswers: ["Let me share my screen."],
        hint: "Sunum baslatirken kullanilir.",
        explanation: "\"Let me...\" kendi aksiyonunu duyurmak icin uygundur.",
      },
      {
        id: "meeting-ex-5",
        type: "translate-written",
        prompt: "Cumleyi Ingilizceye cevir.",
        instructions: "Toplantida soylenebilecek net bir ceviri yaz.",
        sourceText: "Bir sey eklemek icin araya girebilir miyim?",
        correctAnswers: ["Can I jump in for a moment?", "May I jump in for a moment?"],
        hint: "jump in kalibini kullan.",
        explanation: "Jump in, toplanti akisi icinde kisa soz alma anlamina gelir.",
      },
    ],
  },
  // ── 4. B1 İş Görüşmesi ──────────────────────────────────────────────
  {
    id: "community-seed-job-interview",
    title: "B1 Is Gorusmesi",
    description: "Is gorusmesinde kendinizi tanitmak, deneyimlerinizi anlatmak ve sorulara profesyonelce cevap vermek icin pratik seti.",
    category: "Is Ingilizcesi",
    difficulty: "intermediate" as const,
    sourceLanguage: "Turkish",
    targetLanguage: "English",
    icon: "🤝",
    tags: ["is-gorusmesi", "kariyer", "profesyonel", "B1"],
    objectives: [
      "Kendinizi kisa ve etkili tanitmak",
      "Deneyim ve becerilerinizi ifade etmek",
      "Gorusme sorularina uygun cevaplar verebilmek",
    ],
    estimatedMinutes: 8,
    words: [
      { id: "job-word-1", term: "is deneyimi", translation: "work experience", example: "Uc yillik is deneyimim var.", note: "CV ve gorusmelerde en sik kullanilan ifade." },
      { id: "job-word-2", term: "guclu yonler", translation: "strengths", example: "Guclu yonlerim arasinda takim calismasi var.", note: "What are your strengths? sorusuna cevap." },
      { id: "job-word-3", term: "maas beklentisi", translation: "salary expectation", example: "Maas beklentiniz nedir?", note: "HR sorulari arasinda cok yaygin." },
      { id: "job-word-4", term: "basvurmak", translation: "apply for", example: "Bu pozisyona basvurmak istiyorum.", note: "Apply for + pozisyon adi." },
    ],
    exercises: [
      {
        id: "job-ex-1",
        type: "multiple-choice",
        prompt: "\"Guclu yonlerim arasinda takim calismasi var\" ifadesine en yakin secenek?",
        instructions: "Gorusmeye uygun profesyonel tonu sec.",
        options: ["One of my strengths is teamwork.", "I am team.", "My team is strong.", "Strength works team."],
        correctAnswers: ["One of my strengths is teamwork."],
        hint: "Strengths = guclu yonler.",
        explanation: "\"One of my strengths is...\" is gorusmelerinde cok kullanilan bir kaliptir.",
      },
      {
        id: "job-ex-2",
        type: "matching",
        prompt: "Is gorusmesi terimlerini eslestir.",
        instructions: "Her Turkce ifadeyi dogru Ingilizce karsiligiyla birlestir.",
        pairs: [
          { id: "job-pair-1", left: "is deneyimi", right: "work experience" },
          { id: "job-pair-2", left: "maas beklentisi", right: "salary expectation" },
          { id: "job-pair-3", left: "basvurmak", right: "apply for" },
        ],
        hint: "Uc terim de CV ve gorusmelerde gecen klasik ifadeler.",
        explanation: "Bu terimler hemen hemen her is gorusmesinde karsimiza cikar.",
      },
      {
        id: "job-ex-3",
        type: "fill-blank",
        prompt: "\"I have three years of ___.\"",
        instructions: "Is gecmisini ifade eden boslugu doldur.",
        correctAnswers: ["work experience"],
        hint: "Kelime bankasindaki ilk ifade.",
        explanation: "Work experience, is gecmisini ozetleyen standart ifadedir.",
      },
      {
        id: "job-ex-4",
        type: "speech-to-text",
        prompt: "Dinle ve gorusme cevabini yaz.",
        instructions: "Okunan cumleyi ayni sekilde yaz.",
        voiceText: "I would like to apply for the marketing position.",
        correctAnswers: ["I would like to apply for the marketing position."],
        hint: "Resmi bir basvuru cumlesi.",
        explanation: "\"I would like to apply for...\" resmi is basvurularinda standart kaliptir.",
      },
      {
        id: "job-ex-5",
        type: "translate-written",
        prompt: "Cumleyi Ingilizceye cevir.",
        instructions: "Gorusmede soylenebilecek profesyonel bir ceviri yaz.",
        sourceText: "Guclu yonlerim arasinda problem cozme becerisi var.",
        correctAnswers: ["One of my strengths is problem-solving.", "One of my strengths is problem solving."],
        hint: "Strengths ve problem-solving kaliplarini kullan.",
        explanation: "Problem-solving, is gorusmelerinde en cok bahsedilen becerilerden biridir.",
      },
    ],
  },
  // ── 5. Otel Check-in ────────────────────────────────────────────────
  {
    id: "community-seed-hotel-checkin",
    title: "Otel Check-in",
    description: "Otele giris yaparken resepsiyon gorevlisiyle iletisim kurmak icin gerekli kaliplar.",
    category: "Seyahat",
    difficulty: "intermediate" as const,
    sourceLanguage: "Turkish",
    targetLanguage: "English",
    icon: "🏨",
    tags: ["otel", "seyahat", "konaklama", "check-in"],
    objectives: [
      "Rezervasyon bilgilerinizi iletmek",
      "Oda tercihi belirtmek",
      "Otel hizmetleri hakkinda soru sormak",
    ],
    estimatedMinutes: 7,
    words: [
      { id: "hotel-word-1", term: "rezervasyon", translation: "reservation", example: "Bir rezervasyonum var.", note: "I have a reservation kalibini kullan." },
      { id: "hotel-word-2", term: "deniz manzarali oda", translation: "sea-view room", example: "Deniz manzarali oda var mi?", note: "Room with a view da kullanilabilir." },
      { id: "hotel-word-3", term: "kahvalti dahil mi?", translation: "Is breakfast included?", example: "Kahvalti fiyata dahil mi?", note: "Included = dahil." },
      { id: "hotel-word-4", term: "geç cikis", translation: "late checkout", example: "Gec cikis mumkun mu?", note: "Genelde 12:00 yerine 14:00." },
    ],
    exercises: [
      {
        id: "hotel-ex-1",
        type: "multiple-choice",
        prompt: "\"Bir rezervasyonum var\" cumlesine en yakin Ingilizce hangisi?",
        instructions: "Resepsiyonda soylenebilecek dogal cevabi sec.",
        options: ["I have a reservation.", "Reservation is me.", "My reserve hotel.", "I am booking."],
        correctAnswers: ["I have a reservation."],
        hint: "Reservation kelimesini kullan.",
        explanation: "\"I have a reservation\" otel girisinde en standart kaliptir.",
      },
      {
        id: "hotel-ex-2",
        type: "matching",
        prompt: "Otel terimlerini eslestir.",
        instructions: "Turkce ifadeleri Ingilizce karsiliklarla birlestir.",
        pairs: [
          { id: "hotel-pair-1", left: "deniz manzarali oda", right: "sea-view room" },
          { id: "hotel-pair-2", left: "kahvalti dahil mi?", right: "Is breakfast included?" },
          { id: "hotel-pair-3", left: "gec cikis", right: "late checkout" },
        ],
        hint: "Her biri otele giris veya konaklama hakkinda.",
        explanation: "Bu uc ifade otel konaklamasinda en sik sorulanlar arasinda.",
      },
      {
        id: "hotel-ex-3",
        type: "fill-blank",
        prompt: "\"Is breakfast ___?\"",
        instructions: "Kahvaltinin fiyata dahil olup olmadigini soran eksik kelimeyi yaz.",
        correctAnswers: ["included"],
        hint: "Dahil = ?",
        explanation: "Included, bir hizmetin fiyata dahil oldugunu ifade eder.",
      },
      {
        id: "hotel-ex-4",
        type: "speech-to-text",
        prompt: "Dinle ve otel cumlesi yaz.",
        instructions: "Okunan cumleyi ayni sekilde yaz.",
        voiceText: "I have a reservation under the name Smith.",
        correctAnswers: ["I have a reservation under the name Smith."],
        hint: "Isim belirterek check-in yapiliyor.",
        explanation: "\"Under the name...\" rezervasyon ismi belirtirken kullanilir.",
      },
      {
        id: "hotel-ex-5",
        type: "translate-written",
        prompt: "Cumleyi Ingilizceye cevir.",
        instructions: "Resepsiyonda soylenebilecek dogal bir cumle kur.",
        sourceText: "Gec cikis mumkun mu?",
        correctAnswers: ["Is late checkout possible?", "Is a late checkout possible?", "Can I get a late checkout?"],
        hint: "Late checkout kalibini kullan.",
        explanation: "Late checkout, standart cikis saatinden sonra odayi kullanmak icin yapilan istektir.",
      },
    ],
  },
  // ── 6. Doktor Randevusu ──────────────────────────────────────────────
  {
    id: "community-seed-doctor-appointment",
    title: "Doktor Randevusu",
    description: "Doktor randevusu almak, sikayet bildirmek ve tedavi hakkinda soru sormak icin gerekli kaliplar.",
    category: "Saglik",
    difficulty: "intermediate" as const,
    sourceLanguage: "Turkish",
    targetLanguage: "English",
    icon: "🏥",
    tags: ["doktor", "saglik", "randevu", "hastalik"],
    objectives: [
      "Randevu almak ve iptal etmek",
      "Sikayetlerinizi acik ifade etmek",
      "Tedavi ve ilac hakkinda soru sormak",
    ],
    estimatedMinutes: 8,
    words: [
      { id: "doc-word-1", term: "randevu almak", translation: "make an appointment", example: "Bir randevu almak istiyorum.", note: "Book an appointment da kullanilir." },
      { id: "doc-word-2", term: "bas agrisi", translation: "headache", example: "Iki gundur bas agrim var.", note: "I have a headache kalibini kullan." },
      { id: "doc-word-3", term: "recete", translation: "prescription", example: "Recete yazabilir misiniz?", note: "Ilac icin doktordan alinan belge." },
      { id: "doc-word-4", term: "alerji", translation: "allergy", example: "Penisiline alerjim var.", note: "I am allergic to... kalibi ile kullanilir." },
    ],
    exercises: [
      {
        id: "doc-ex-1",
        type: "multiple-choice",
        prompt: "\"Bir randevu almak istiyorum\" ifadesine en yakin Ingilizce hangisi?",
        instructions: "Hasta olarak soylenebilecek en uygun cevabi sec.",
        options: ["I would like to make an appointment.", "I am appointment.", "Give me doctor.", "Appointment wants me."],
        correctAnswers: ["I would like to make an appointment."],
        hint: "Make an appointment = randevu almak.",
        explanation: "\"I would like to make an appointment\" doktor randevusu icin en standart kaliptir.",
      },
      {
        id: "doc-ex-2",
        type: "matching",
        prompt: "Saglik terimlerini eslestir.",
        instructions: "Turkce ifadeleri Ingilizce karsiliklarla birlestir.",
        pairs: [
          { id: "doc-pair-1", left: "bas agrisi", right: "headache" },
          { id: "doc-pair-2", left: "recete", right: "prescription" },
          { id: "doc-pair-3", left: "alerji", right: "allergy" },
        ],
        hint: "Saglik ve ilac ile ilgili temel terimler.",
        explanation: "Bu uc terim doktor ziyaretlerinde en cok ihtiyac duyulanlardir.",
      },
      {
        id: "doc-ex-3",
        type: "fill-blank",
        prompt: "\"I have had a ___ for two days.\"",
        instructions: "Iki gundur devam eden sikayeti ifade eden kelimeyi yaz.",
        correctAnswers: ["headache"],
        hint: "Bas ile ilgili bir sikayet.",
        explanation: "Headache, en yaygin doktor sikayet ifadelerinden biridir.",
      },
      {
        id: "doc-ex-4",
        type: "speech-to-text",
        prompt: "Dinle ve doktor diyalogunu yaz.",
        instructions: "Okunan cumleyi ayni sekilde yaz.",
        voiceText: "I am allergic to penicillin.",
        correctAnswers: ["I am allergic to penicillin."],
        hint: "Bir ilac alerjisi belirtiliyor.",
        explanation: "\"I am allergic to...\" alerji bildirirken kritik onem tasiyan bir kaliptir.",
      },
      {
        id: "doc-ex-5",
        type: "translate-written",
        prompt: "Cumleyi Ingilizceye cevir.",
        instructions: "Doktora soylenebilecek dogal bir cumle kur.",
        sourceText: "Recete yazabilir misiniz?",
        correctAnswers: ["Can you write a prescription?", "Could you write me a prescription?"],
        hint: "Prescription kelimesini kullan.",
        explanation: "Write a prescription, recete yazmak icin standart Ingilizce ifadedir.",
      },
    ],
  },
  // ── 7. Restoranda Yemek ──────────────────────────────────────────────
  {
    id: "community-seed-restaurant-dining",
    title: "Restoranda Yemek",
    description: "Restoranda masa ayirtmak, menu sormak ve siparis vermek icin gerekli gunluk kaliplar.",
    category: "Gunluk Hayat",
    difficulty: "beginner" as const,
    sourceLanguage: "Turkish",
    targetLanguage: "English",
    icon: "🍽️",
    tags: ["restoran", "yemek", "siparis", "baslangic"],
    objectives: [
      "Masa ayirtma ve menu isteme",
      "Yemek siparisi verebilmek",
      "Hesap isteme ve bahsis birakma",
    ],
    estimatedMinutes: 6,
    words: [
      { id: "rest-word-1", term: "masa ayirtmak", translation: "book a table", example: "Iki kisilik masa ayirtmak istiyorum.", note: "Reserve a table da kullanilir." },
      { id: "rest-word-2", term: "menuyu gormek", translation: "see the menu", example: "Menuyu gorebilir miyim?", note: "Menu yerine bazen wine list de sorulur." },
      { id: "rest-word-3", term: "ana yemek", translation: "main course", example: "Ana yemek olarak ne onerirsiniz?", note: "Entree Amerikan Ingilizcesinde kullanilir." },
      { id: "rest-word-4", term: "bahsis", translation: "tip", example: "Bahsis birakmak istiyorum.", note: "Leave a tip kalibi ile kullanilir." },
    ],
    exercises: [
      {
        id: "rest-ex-1",
        type: "multiple-choice",
        prompt: "\"Menuyu gorebilir miyim?\" cumlesine en yakin Ingilizce hangisi?",
        instructions: "Garsonla konusurken kullanilacak en dogal ifadeyi sec.",
        options: ["Could I see the menu, please?", "Menu is where?", "I am the menu.", "Show food me."],
        correctAnswers: ["Could I see the menu, please?"],
        hint: "See the menu = menuyu gormek.",
        explanation: "\"Could I see the menu?\" restoranda cok kullanilan nazik bir istektir.",
      },
      {
        id: "rest-ex-2",
        type: "matching",
        prompt: "Restoran ifadelerini eslestir.",
        instructions: "Turkce ifadeleri Ingilizce karsiliklarla birlestir.",
        pairs: [
          { id: "rest-pair-1", left: "masa ayirtmak", right: "book a table" },
          { id: "rest-pair-2", left: "ana yemek", right: "main course" },
          { id: "rest-pair-3", left: "bahsis", right: "tip" },
        ],
        hint: "Restoran surecinin farkli asamalarindaki terimler.",
        explanation: "Bu uc ifade restoran deneyiminin temel taslarini olusturur.",
      },
      {
        id: "rest-ex-3",
        type: "fill-blank",
        prompt: "\"I would like to ___ a table for two.\"",
        instructions: "Masa ayirtmak icin eksik fiili yaz.",
        correctAnswers: ["book", "reserve"],
        hint: "Ayirtmak anlamina gelen fiil.",
        explanation: "Book veya reserve, masa ayirtmak icin kullanilan iki yaygin fiildir.",
      },
      {
        id: "rest-ex-4",
        type: "speech-to-text",
        prompt: "Dinle ve restoran siparisini yaz.",
        instructions: "Okunan cumleyi ayni sekilde yaz.",
        voiceText: "Could I see the menu, please?",
        correctAnswers: ["Could I see the menu, please?"],
        hint: "Nazik bir menu istegi.",
        explanation: "\"Could I...\" restoranda kullanilan kibarca istek kalibidir.",
      },
      {
        id: "rest-ex-5",
        type: "translate-written",
        prompt: "Cumleyi Ingilizceye cevir.",
        instructions: "Restoranda soylenebilecek dogal bir cumle kur.",
        sourceText: "Ana yemek olarak ne onerirsiniz?",
        correctAnswers: ["What do you recommend for the main course?", "What would you recommend for the main course?"],
        hint: "Main course ve recommend kaliplarini kullan.",
        explanation: "Recommend, garsondan oneri isterken kullanilan standart fiildir.",
      },
    ],
  },
  // ── 8. Kıyafet Alışverişi ────────────────────────────────────────────
  {
    id: "community-seed-shopping-clothes",
    title: "Kiyafet Alisverisi",
    description: "Magaza icerisinde beden sormak, fiyat ogrenmek ve satin almak icin pratik seti.",
    category: "Gunluk Hayat",
    difficulty: "beginner" as const,
    sourceLanguage: "Turkish",
    targetLanguage: "English",
    icon: "🛍️",
    tags: ["alisveris", "kiyafet", "magaza", "baslangic"],
    objectives: [
      "Beden ve renk sorabilmek",
      "Fiyat ve indirim hakkinda bilgi almak",
      "Satin alma ve iade islemi yapabilmek",
    ],
    estimatedMinutes: 6,
    words: [
      { id: "shop-word-1", term: "beden", translation: "size", example: "Bu tisortun medium bedeni var mi?", note: "Small, medium, large boyutlar." },
      { id: "shop-word-2", term: "indirim", translation: "discount", example: "Bu urun indirimde mi?", note: "On sale = indirimde." },
      { id: "shop-word-3", term: "denemek", translation: "try on", example: "Bunu deneyebilir miyim?", note: "Try on = kiyafet denemek." },
      { id: "shop-word-4", term: "iade etmek", translation: "return", example: "Bu urunu iade edebilir miyim?", note: "Return policy = iade politikasi." },
    ],
    exercises: [
      {
        id: "shop-ex-1",
        type: "multiple-choice",
        prompt: "\"Bunu deneyebilir miyim?\" ifadesine en yakin Ingilizce hangisi?",
        instructions: "Magazada kullanilacak en dogal ifadeyi sec.",
        options: ["Can I try this on?", "I am trying.", "This tries me.", "Try is possible?"],
        correctAnswers: ["Can I try this on?"],
        hint: "Try on = denemek.",
        explanation: "\"Can I try this on?\" kiyafet denerken en yaygin kullanilan kaliptir.",
      },
      {
        id: "shop-ex-2",
        type: "matching",
        prompt: "Alisveris terimlerini eslestir.",
        instructions: "Turkce ifadeleri Ingilizce karsiliklarla birlestir.",
        pairs: [
          { id: "shop-pair-1", left: "indirim", right: "discount" },
          { id: "shop-pair-2", left: "denemek", right: "try on" },
          { id: "shop-pair-3", left: "iade etmek", right: "return" },
        ],
        hint: "Alisveris surecinin farkli asamalari.",
        explanation: "Indirim sormak, kiyafet denemek ve iade etmek magazada en temel islemlerdir.",
      },
      {
        id: "shop-ex-3",
        type: "fill-blank",
        prompt: "\"Do you have this in a different ___?\"",
        instructions: "Farkli beden istedigini ifade eden kelimeyi yaz.",
        correctAnswers: ["size"],
        hint: "Beden = ?",
        explanation: "Size, kiyafet bedeni icin kullanilan standart terimdir.",
      },
      {
        id: "shop-ex-4",
        type: "speech-to-text",
        prompt: "Dinle ve alisveris cumlesi yaz.",
        instructions: "Okunan cumleyi ayni sekilde yaz.",
        voiceText: "Is this on sale?",
        correctAnswers: ["Is this on sale?"],
        hint: "Indirim hakkinda kisa bir soru.",
        explanation: "\"On sale\" bir urunun indirimde oldugunu ifade eder.",
      },
      {
        id: "shop-ex-5",
        type: "translate-written",
        prompt: "Cumleyi Ingilizceye cevir.",
        instructions: "Magazada soylenebilecek dogal bir cumle kur.",
        sourceText: "Bu urunu iade edebilir miyim?",
        correctAnswers: ["Can I return this item?", "Can I return this?"],
        hint: "Return kelimesini kullan.",
        explanation: "Return, iade islemi icin kullanilan standart fiildir.",
      },
    ],
  },
  // ── 9. Banka İşlemleri ───────────────────────────────────────────────
  {
    id: "community-seed-bank-account",
    title: "Banka Islemleri",
    description: "Bankada hesap acmak, para transferi yapmak ve kart islemleri hakkinda konusmak icin gerekli kaliplar.",
    category: "Resmi Islemler",
    difficulty: "intermediate" as const,
    sourceLanguage: "Turkish",
    targetLanguage: "English",
    icon: "🏦",
    tags: ["banka", "finans", "resmi", "hesap"],
    objectives: [
      "Hesap acma talebi yapabilmek",
      "Para transferi ve islem sorgulamak",
      "Kart kaybi veya sorun bildirmek",
    ],
    estimatedMinutes: 8,
    words: [
      { id: "bank-word-1", term: "hesap acmak", translation: "open an account", example: "Hesap acmak istiyorum.", note: "Savings account = birikim hesabi." },
      { id: "bank-word-2", term: "para transferi", translation: "money transfer", example: "Baska bir bankaya para transferi yapmak istiyorum.", note: "Wire transfer = havale." },
      { id: "bank-word-3", term: "bakiye sorgulamak", translation: "check the balance", example: "Bakiyemi ogrenmek istiyorum.", note: "Balance = hesap bakiyesi." },
      { id: "bank-word-4", term: "kartimi kaybettim", translation: "I lost my card", example: "Kartimi kaybettim, ne yapmaliyim?", note: "Block/cancel the card = karti iptal ettirmek." },
    ],
    exercises: [
      {
        id: "bank-ex-1",
        type: "multiple-choice",
        prompt: "\"Hesap acmak istiyorum\" ifadesine en yakin Ingilizce hangisi?",
        instructions: "Banka gorevlisine soylenebilecek en uygun cevabi sec.",
        options: ["I would like to open an account.", "I am account.", "Open is me.", "Account wants opening."],
        correctAnswers: ["I would like to open an account."],
        hint: "Open an account = hesap acmak.",
        explanation: "\"I would like to open an account\" bankada hesap acmak icin standart kaliptir.",
      },
      {
        id: "bank-ex-2",
        type: "matching",
        prompt: "Banka terimlerini eslestir.",
        instructions: "Turkce ifadeleri Ingilizce karsiliklarla birlestir.",
        pairs: [
          { id: "bank-pair-1", left: "para transferi", right: "money transfer" },
          { id: "bank-pair-2", left: "bakiye sorgulamak", right: "check the balance" },
          { id: "bank-pair-3", left: "kartimi kaybettim", right: "I lost my card" },
        ],
        hint: "Bankadaki farkli islem turlerini ifade ederler.",
        explanation: "Bu uc kalip bankada en sik karsilasilan durumlardir.",
      },
      {
        id: "bank-ex-3",
        type: "fill-blank",
        prompt: "\"I would like to ___ the balance.\"",
        instructions: "Bakiye sorgulamak icin eksik fiili yaz.",
        correctAnswers: ["check"],
        hint: "Kontrol etmek, sorgulamak anlaminda.",
        explanation: "Check the balance, hesap bakiyesini sorgulamak icin standart ifadedir.",
      },
      {
        id: "bank-ex-4",
        type: "speech-to-text",
        prompt: "Dinle ve banka islem cumlesi yaz.",
        instructions: "Okunan cumleyi ayni sekilde yaz.",
        voiceText: "I lost my card. Can you block it?",
        correctAnswers: ["I lost my card. Can you block it?"],
        hint: "Kart kaybi ve islem talebi.",
        explanation: "Block, karti iptal ettirmek veya gecici olarak durdurmak anlaminda kullanilir.",
      },
      {
        id: "bank-ex-5",
        type: "translate-written",
        prompt: "Cumleyi Ingilizceye cevir.",
        instructions: "Bankada soylenebilecek dogal bir cumle kur.",
        sourceText: "Baska bir bankaya para transferi yapmak istiyorum.",
        correctAnswers: ["I would like to make a money transfer to another bank.", "I want to transfer money to another bank."],
        hint: "Money transfer ve another bank kaliplarini kullan.",
        explanation: "Money transfer, bankalar arasi para gonderimi icin standart ifadedir.",
      },
    ],
  },
  // ── 10. Acil Yardım İsteme ───────────────────────────────────────────
  {
    id: "community-seed-emergency-help",
    title: "Acil Yardim Isteme",
    description: "Acil durumlarda yardim cagirmak, konum bildirmek ve temel bilgileri iletmek icin hayati kaliplar.",
    category: "Acil Durumlar",
    difficulty: "intermediate" as const,
    sourceLanguage: "Turkish",
    targetLanguage: "English",
    icon: "🚑",
    tags: ["acil", "yardim", "guvenlik", "saglik"],
    objectives: [
      "Acil yardim hattini arayabilmek",
      "Konumunuzu ve durumu kisa ifade etmek",
      "Temel tibbi ve guvenlik bilgisi verebilmek",
    ],
    estimatedMinutes: 7,
    words: [
      { id: "emer-word-1", term: "acil durum", translation: "emergency", example: "Bu bir acil durum.", note: "Emergency services = acil servisler." },
      { id: "emer-word-2", term: "ambulans cagirmak", translation: "call an ambulance", example: "Lutfen bir ambulans cagirin.", note: "911 (ABD) veya 112 (TR/AB) aranir." },
      { id: "emer-word-3", term: "yardim edin", translation: "help me", example: "Lutfen yardim edin!", note: "Help! tek basina da kullanilir." },
      { id: "emer-word-4", term: "adres vermek", translation: "give the address", example: "Adresimiz Ataturk Caddesi 15.", note: "Location da kullanilabilir." },
    ],
    exercises: [
      {
        id: "emer-ex-1",
        type: "multiple-choice",
        prompt: "\"Lutfen bir ambulans cagirin\" ifadesine en yakin Ingilizce hangisi?",
        instructions: "Acil durumda en etkili ifadeyi sec.",
        options: ["Please call an ambulance.", "Ambulance is here.", "I am the ambulance.", "Call is ambulance."],
        correctAnswers: ["Please call an ambulance."],
        hint: "Call an ambulance = ambulans cagirmak.",
        explanation: "\"Please call an ambulance\" acil durumlarda hizli ve net iletisim saglar.",
      },
      {
        id: "emer-ex-2",
        type: "matching",
        prompt: "Acil durum ifadelerini eslestir.",
        instructions: "Turkce ifadeleri Ingilizce karsiliklarla birlestir.",
        pairs: [
          { id: "emer-pair-1", left: "acil durum", right: "emergency" },
          { id: "emer-pair-2", left: "yardim edin", right: "help me" },
          { id: "emer-pair-3", left: "ambulans cagirmak", right: "call an ambulance" },
        ],
        hint: "Hepsi acil durumda iletisimi saglayan temel ifadeler.",
        explanation: "Bu uc ifade acil durumlarda bilmeniz gereken en kritik kaliplardir.",
      },
      {
        id: "emer-ex-3",
        type: "fill-blank",
        prompt: "\"This is an ___. Please send help.\"",
        instructions: "Acil durumu ifade eden kelimeyi yaz.",
        correctAnswers: ["emergency"],
        hint: "Acil durum = ?",
        explanation: "Emergency kelimesi yardim hattinda durumun ciddiyetini bildirir.",
      },
      {
        id: "emer-ex-4",
        type: "speech-to-text",
        prompt: "Dinle ve acil durum cumlesi yaz.",
        instructions: "Okunan cumleyi ayni sekilde yaz.",
        voiceText: "I need help. Please call an ambulance.",
        correctAnswers: ["I need help. Please call an ambulance."],
        hint: "Yardim istegi ve ambulans cagrisi.",
        explanation: "Acil durumlarda kisa ve net cumleler hayat kurtarir.",
      },
      {
        id: "emer-ex-5",
        type: "translate-written",
        prompt: "Cumleyi Ingilizceye cevir.",
        instructions: "Acil durumda soylenebilecek net bir cumle kur.",
        sourceText: "Bu bir acil durum. Adresimiz Ataturk Caddesi 15.",
        correctAnswers: ["This is an emergency. Our address is 15 Ataturk Street.", "This is an emergency. Our address is Ataturk Street 15."],
        hint: "Emergency ve address kaliplarini kullan.",
        explanation: "Acil durumlarda adres bilgisi vermek yardimin hizli ulasmasi icin kritiktir.",
      },
    ],
  },
  // ── 11. Ev Kiralama ──────────────────────────────────────────────────
  {
    id: "community-seed-rental-apartment",
    title: "Ev Kiralama",
    description: "Ev aramak, emlakciyla iletisim kurmak ve kira sartlarini konusmak icin ileri seviye pratik seti.",
    category: "Gunluk Hayat",
    difficulty: "advanced" as const,
    sourceLanguage: "Turkish",
    targetLanguage: "English",
    icon: "🏠",
    tags: ["ev", "kiralama", "emlak", "ileri-seviye"],
    objectives: [
      "Ilan sormak ve ev gezmek",
      "Kira ve depozito kosullarini konusmak",
      "Sozlesme detaylari hakkinda soru sormak",
    ],
    estimatedMinutes: 9,
    words: [
      { id: "rent-word-1", term: "aylik kira", translation: "monthly rent", example: "Aylik kira ne kadar?", note: "Rent alone = kira." },
      { id: "rent-word-2", term: "depozito", translation: "security deposit", example: "Depozito ne kadar?", note: "Genelde 1-2 aylik kira tutarinda." },
      { id: "rent-word-3", term: "kira sozlesmesi", translation: "lease agreement", example: "Kira sozlesmesi ne kadar sureli?", note: "Lease = uzun sureli kira sozlesmesi." },
      { id: "rent-word-4", term: "esyali", translation: "furnished", example: "Daire esyali mi?", note: "Unfurnished = esyasiz." },
    ],
    exercises: [
      {
        id: "rent-ex-1",
        type: "multiple-choice",
        prompt: "\"Aylik kira ne kadar?\" sorusuna en yakin Ingilizce hangisi?",
        instructions: "Ev sahibine veya emlakciya sorulabilecek en dogal ifadeyi sec.",
        options: ["How much is the monthly rent?", "Rent is how money?", "Monthly is the rent?", "I am the rent."],
        correctAnswers: ["How much is the monthly rent?"],
        hint: "Monthly rent = aylik kira.",
        explanation: "\"How much is the monthly rent?\" kira sormak icin en standart kaliptir.",
      },
      {
        id: "rent-ex-2",
        type: "matching",
        prompt: "Ev kiralama terimlerini eslestir.",
        instructions: "Turkce ifadeleri Ingilizce karsiliklarla birlestir.",
        pairs: [
          { id: "rent-pair-1", left: "depozito", right: "security deposit" },
          { id: "rent-pair-2", left: "kira sozlesmesi", right: "lease agreement" },
          { id: "rent-pair-3", left: "esyali", right: "furnished" },
        ],
        hint: "Kiralama surecinin farkli asamalarina ait terimler.",
        explanation: "Depozito, sozlesme ve esya durumu ev kiralamanin temel konularini olusturur.",
      },
      {
        id: "rent-ex-3",
        type: "fill-blank",
        prompt: "\"Is the apartment ___?\"",
        instructions: "Dairenin esyali olup olmadigini soran kelimeyi yaz.",
        correctAnswers: ["furnished"],
        hint: "Esyali = ?",
        explanation: "Furnished, dairenin mobilyali oldugunu ifade eder. Karşıtı unfurnished'dir.",
      },
      {
        id: "rent-ex-4",
        type: "speech-to-text",
        prompt: "Dinle ve ev kiralama cumlesi yaz.",
        instructions: "Okunan cumleyi ayni sekilde yaz.",
        voiceText: "How long is the lease agreement?",
        correctAnswers: ["How long is the lease agreement?"],
        hint: "Sozlesme suresi soruluyor.",
        explanation: "Lease agreement suresi genelde 6 ay veya 1 yil olarak belirlenir.",
      },
      {
        id: "rent-ex-5",
        type: "translate-written",
        prompt: "Cumleyi Ingilizceye cevir.",
        instructions: "Emlakciyla konusurken soylenebilecek dogal bir cumle kur.",
        sourceText: "Depozito ne kadar ve ne zaman iade ediliyor?",
        correctAnswers: ["How much is the security deposit and when is it refunded?", "How much is the deposit and when is it returned?"],
        hint: "Security deposit ve refund kaliplarini kullan.",
        explanation: "Depozito miktari ve iade kosullari kiralama surecinin en onemli detaylarindan biridir.",
      },
    ],
  },
  // ── 12. Counter-Strike 2 – Takım İletişimi ───────────────────────────
  {
    id: "community-seed-cs2-comms",
    title: "CS2 Takim Iletisimi",
    description: "Counter-Strike 2'de takim arkadaşlarinla Ingilizce iletişim kurmak icin gerekli callout'lar, komutlar ve oyun icin kaliplar.",
    category: "Oyun Ingilizcesi",
    difficulty: "beginner" as const,
    sourceLanguage: "Turkish",
    targetLanguage: "English",
    icon: "🎮",
    tags: ["cs2", "oyun", "fps", "takim-iletisimi", "gaming"],
    objectives: [
      "Dusman konumu bildirmek (callout)",
      "Ekonomi ve satin alma komutlari vermek",
      "Taktik ve yardim istekleri iletmek",
    ],
    estimatedMinutes: 8,
    words: [
      { id: "cs2-word-1", term: "dusman gordum", translation: "enemy spotted", example: "Enemy spotted, Long A!", note: "Dusman gordugunde takima haber ver." },
      { id: "cs2-word-2", term: "ekonomi turu", translation: "eco round", example: "Let's eco this round.", note: "Silah almadan para biriktirme turu." },
      { id: "cs2-word-3", term: "bombayı birak", translation: "drop the bomb", example: "Drop the bomb at B site.", note: "Bomb carrier'a soylenir." },
      { id: "cs2-word-4", term: "beni koru", translation: "cover me", example: "Cover me, I'm planting.", note: "Bomba dikerken veya ilerlerken kullanilir." },
    ],
    exercises: [
      {
        id: "cs2-ex-1",
        type: "multiple-choice",
        prompt: "Takim arkadasin bombaya yaklasiyorsun ama korunmaya ihtiyacin var. Ne dersin?",
        instructions: "Oyun icinde en dogal ve anlasilir ifadeyi sec.",
        options: ["Cover me, I'm planting.", "Help me bomb is here.", "I am the bomb.", "Bomb wants me."],
        correctAnswers: ["Cover me, I'm planting."],
        hint: "Cover me = beni koru, planting = bomba dikme.",
        explanation: "\"Cover me, I'm planting\" CS2'de bomba dikerken en sik kullanilan callout'tur.",
      },
      {
        id: "cs2-ex-2",
        type: "matching",
        prompt: "CS2 oyun icin terimlerini eslestir.",
        instructions: "Turkce ifadeleri dogru Ingilizce oyun karsiliklarla birlestir.",
        pairs: [
          { id: "cs2-pair-1", left: "dusman gordum", right: "enemy spotted" },
          { id: "cs2-pair-2", left: "ekonomi turu", right: "eco round" },
          { id: "cs2-pair-3", left: "beni koru", right: "cover me" },
          { id: "cs2-pair-4", left: "bombayı birak", right: "drop the bomb" },
        ],
        hint: "Hepsi CS2 mac icinde cok sik duyulan ifadeler.",
        explanation: "Bu dort terim rekabetci CS2 maclarinda her raundda kullanilir.",
      },
      {
        id: "cs2-ex-3",
        type: "fill-blank",
        prompt: "\"___ spotted at B Long!\"",
        instructions: "Dusman gordugunde yaptigin callout'un eksik kelimesini yaz.",
        correctAnswers: ["Enemy"],
        hint: "Dusman = ?",
        explanation: "\"Enemy spotted\" CS2'de dusman pozisyonu bildirmenin standart yoludur.",
      },
      {
        id: "cs2-ex-4",
        type: "speech-to-text",
        prompt: "Dinle ve oyun icin callout'u yaz.",
        instructions: "Okunan cumleyi ayni sekilde yaz.",
        voiceText: "Let's eco this round, save your money.",
        correctAnswers: ["Let's eco this round, save your money."],
        hint: "Ekonomi turu hakkinda bir cagri.",
        explanation: "\"Let's eco\" takim ekonomisini yonetmek icin raund basinda yapilan standart cagridir.",
      },
      {
        id: "cs2-ex-5",
        type: "translate-written",
        prompt: "Cumleyi Ingilizceye cevir.",
        instructions: "Mac icinde takim arkadaşlarina soylenebilecek dogal bir oyun cumlesi kur.",
        sourceText: "Beni koru, bombayı dikiyorum.",
        correctAnswers: ["Cover me, I'm planting.", "Cover me, I'm planting the bomb."],
        hint: "Cover me ve planting kaliplarini kullan.",
        explanation: "\"Cover me, I'm planting\" bomba dikerken takim desteği istemek icin en yaygin ifadedir.",
      },
    ],
  },
];

async function upsertCommunityAuthor() {
  await db
    .insert(usersTable)
    .values({
      id: COMMUNITY_AUTHOR_ID,
      email: COMMUNITY_AUTHOR_EMAIL,
      firstName: "DuoTR",
      lastName: "Topluluk",
      profileImageUrl: null,
    })
    .onConflictDoUpdate({
      target: usersTable.id,
      set: {
        email: COMMUNITY_AUTHOR_EMAIL,
        firstName: "DuoTR",
        lastName: "Topluluk",
        profileImageUrl: null,
      },
    });
}

async function upsertLessons() {
  for (const lesson of lessons) {
    await db
      .insert(communityLessonsTable)
      .values({
        ...lesson,
        authorUserId: COMMUNITY_AUTHOR_ID,
        playCount: 0,
        isPublished: true,
      })
      .onConflictDoUpdate({
        target: communityLessonsTable.id,
        set: {
          authorUserId: COMMUNITY_AUTHOR_ID,
          title: lesson.title,
          description: lesson.description,
          category: lesson.category,
          difficulty: lesson.difficulty,
          sourceLanguage: lesson.sourceLanguage,
          targetLanguage: lesson.targetLanguage,
          icon: lesson.icon,
          tags: lesson.tags,
          objectives: lesson.objectives,
          words: lesson.words,
          exercises: lesson.exercises,
          estimatedMinutes: lesson.estimatedMinutes,
          isPublished: true,
          updatedAt: new Date(),
        },
      });
  }
}

async function main() {
  await upsertCommunityAuthor();
  await upsertLessons();

  console.log(`Seed tamamlandi: ${lessons.length} ornek topluluk dersi hazir.`);
  for (const lesson of lessons) {
    console.log(`- ${lesson.title}`);
  }
}

main()
  .catch((error) => {
    console.error("Topluluk seed basarisiz:", error);
    process.exit(1);
  })
  .finally(() => {
    process.exit(0);
  });
